controller:
  replicas: 1
  image:
    name: ghcr.io/ruakij/webdav-csi-driver
    tag: dev
    pullPolicy: Always
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 20Mi

node:
  image:
    name: ghcr.io/ruakij/webdav-csi-driver
    tag: dev
    pullPolicy: Always
  resources:
    limits:
      memory: 300Mi
    requests:
      cpu: 10m
      memory: 20Mi

livenessProbe:
  image:
    name: registry.k8s.io/sig-storage/livenessprobe
    tag: v2.11.0
    pullPolicy: IfNotPresent

csiProvisioner:
  image:
    name: registry.k8s.io/sig-storage/csi-provisioner
    tag: v3.6.2
    pullPolicy: IfNotPresent

# Configuration for the default storage class
defaultStorageClass: {}
#  name: "webdav"
#  parameters:
#    # alist folder webdav address
#    share: http://ip:port/dav/media 
#    csi.storage.k8s.io/provisioner-secret-name: "webdav-secrect"
#    csi.storage.k8s.io/provisioner-secret-namespace: "default"
#    csi.storage.k8s.io/node-publish-secret-name: "webdav-secrect"
#    csi.storage.k8s.io/node-publish-secret-namespace: "default"
#  reclaimPolicy: "Delete"
#  volumeBindingMode: Immediate
#  mountOptions: {}
